# Generated by Django 3.2 on 2023-05-10 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rental_return_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 18, 53, 9, 220154)),
        ),
    ]
